#!/bin/bash
# This hook is run after a new virtualenv is activated.
pip install setuptools --upgrade
pip install pip --upgrade
#pip install peep --upgrade
#pip install bpython --upgrade
#pip install ipython --upgrade
#pip install ipdb --upgrade
#pip install bumpversion

echo -e "You probably want a decent REPL, like ipython or bpython\n"
echo -e "and maybe a decent debugger, like ipdb or pudb or pdbpp\n"
echo -e "Consider installing some or all of the following: \npip install objgraph paver yolk sphinx pathlib requests line-profiler check-manifest pyroma zest.releaser pep438 bugjar cricket memprof bumpversion"
